In [1]:
import pandas as pd 
import sqlite3

conn = sqlite3.connect("banco.db")

query = """
    SELECT *
    FROM partidas
;
"""

df_copa = pd.read_sql_query(query, conn)
display(df_copa)

,id,match_id,data_partida,selecao,adversario,gols_feitos,gols_sofridos,finalizacoes_feitas,finalizacoes_sofridas,cartoes_amarelos,cartoes_vermelhos,escanteios,xg,resultado,placar
0,1,211661,2026-06-12 19:00:00,Canada,Bosnia and Herzegovina,1,1,13,8,2,0,9,1.69,Empate,1x1
1,2,211661,2026-06-12 19:00:00,Bosnia and Herzegovina,Canada,1,1,8,13,3,0,4,0.87,Empate,1x1
2,3,204598,2026-06-11 19:00:00,Mexico,South Africa,2,0,16,3,1,1,3,1.50,Vitoria,2x0
3,4,204598,2026-06-11 19:00:00,South Africa,Mexico,0,2,3,16,2,2,1,0.54,Derrota,2x0
4,5,211664,2026-06-12 02:00:00,South Korea,Czech Republic,2,1,15,7,1,0,4,1.65,Vitoria,2x1
5,6,211664,2026-06-12 02:00:00,Czech Republic,South Korea,1,2,7,15,0,0,5,1.04,Derrota,2x1
6,13,204602,2026-06-13 01:00:00,USMNT,Paraguay,4,1,16,9,1,0,3,2.10,Vitoria,4x1
7,14,204602,2026-06-13 01:00:00,Paraguay,USMNT,1,4,9,16,5,0,1,0.80,Derrota,4x1
8,15,204626,2026-06-13 19:00:00,Qatar,Switzerland,1,1,7,26,2,0,3,0.84,Empate,1x1
9,16,204626,2026-06-13 19:00:00,Switzerland,Qatar,1,1,26,7,1,0,10,2.76,Empate,1x1
10,17,204597,2026-06-13 22:00:00,Brazil,Morocco,1,1,13,14,2,0,6,1.42,Empate,1x1
11,18,204597,2026-06-13 22:00:00,Morocco,Brazil,1,1,14,13,0,0,2,1.44,Empate,1x1
12,19,204641,2026-06-14 01:00:00,Haiti,Scotland,0,1,15,9,1,0,4,1.43,Derrota,0x1
13,20,204641,2026-06-14 01:00:00,Scotland,Haiti,1,0,9,15,3,0,3,0.99,Vitoria,0x1
14,21,211658,2026-06-14 04:00:00,Australia,Turkey,2,0,9,30,0,0,5,1.10,Vitoria,2x0
15,22,211658,2026-06-14 04:00:00,Turkey,Australia,0,2,30,9,1,0,8,3.19,Derrota,2x0
16,23,204636,2026-06-14 17:00:00,Germany,Curaçao,7,1,27,8,0,0,8,3.12,Vitoria,7x1
17,24,204636,2026-06-14 17:00:00,Curaçao,Germany,1,7,8,27,0,0,1,0.81,Derrota,7x1
18,25,204604,2026-06-14 20:00:00,Netherlands,Japan,2,2,10,10,3,0,5,1.49,Empate,2x2
19,26,204604,2026-06-14 20:00:00,Japan,Netherlands,2,2,10,10,0,0,4,1.15,Empate,2x2
20,27,204621,2026-06-14 23:00:00,Ivory Coast,Ecuador,1,0,15,12,3,0,3,1.65,Vitoria,1x0
21,28,204621,2026-06-14 23:00:00,Ecuador,Ivory Coast,0,1,12,15,1,0,5,1.16,Derrota,1x0
22,29,211657,2026-06-15 02:00:00,Sweden,Tunisia,5,1,13,6,0,0,4,1.63,Vitoria,5x1
23,30,211657,2026-06-15 02:00:00,Tunisia,Sweden,1,5,6,13,1,0,2,0.83,Derrota,5x1
24,31,204644,2026-06-15 16:00:00,Spain,Cape Verde Islands,0,0,27,6,1,0,11,3.19,Empate,0x0
25,32,204644,2026-06-15 16:00:00,Cape Verde Islands,Spain,0,0,6,27,1,0,1,0.50,Empate,0x0
26,33,204624,2026-06-15 19:00:00,Belgium,Egypt,1,1,15,14,2,0,2,1.62,Empate,1x1
27,34,204624,2026-06-15 19:00:00,Egypt,Belgium,1,1,14,15,2,0,7,1.33,Empate,1x1
28,35,204630,2026-06-15 22:00:00,Saudi Arabia,Uruguay,1,1,7,28,1,0,4,0.86,Empate,1x1
29,36,204630,2026-06-15 22:00:00,Uruguay,Saudi Arabia,1,1,28,7,0,0,14,3.03,Empate,1x1

In [6]:
conn = sqlite3.connect("banco.db")

query = """
    SELECT selecao, SUM(xg) AS xg    
    FROM partidas
    GROUP BY selecao
    HAVING SUM(xg) > (
        SELECT AVG(total)
        FROM(
            SELECT selecao, SUM(xg) AS total
            FROM partidas
            GROUP BY selecao
        )t
    ) ORDER BY xg DESC
;
"""

df_copa = pd.read_sql_query(query, conn)
display(df_copa)

       selecao    xg
0       Turkey  3.19
1      Germany  3.12
2  Switzerland  2.76
3        USMNT  2.10
4       Canada  1.69
5  South Korea  1.65
6  Ivory Coast  1.65
7       Mexico  1.50
8  Netherlands  1.49